version: "3.9"

services:
  db:
    image: postgres:16
    container_name: eventhub_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: eventhub
      POSTGRES_PASSWORD: eventhub
      POSTGRES_DB: eventhub
    ports:
      - "5432:5432"
    volumes:
      - eventhub_pgdata:/var/lib/postgresql/data

volumes:
  eventhub_pgdata:
